# Generated by Django 4.2.14 on 2024-09-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_post_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
