# Generated by Django 4.2.14 on 2024-09-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalStoryExercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("content", models.TextField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educational_story_exercises",
                        to="api_education.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FindPairExercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("text1", models.CharField(max_length=255)),
                ("text2", models.CharField(max_length=255)),
                ("image1", models.ImageField(upload_to="find_pair_images/")),
                ("image2", models.ImageField(upload_to="find_pair_images/")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="find_pair_exercises",
                        to="api_education.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreeTextExercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("prompt", models.TextField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_text_exercises",
                        to="api_education.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignLanguageExercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("video", models.FileField(upload_to="sign_language_videos/")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sign_language_exercises",
                        to="api_education.lesson",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="findpairlesson",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="freetextlesson",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="signlanguagelesson",
            name="lesson",
        ),
        migrations.DeleteModel(
            name="EducationalStoryLesson",
        ),
        migrations.DeleteModel(
            name="FindPairLesson",
        ),
        migrations.DeleteModel(
            name="FreeTextLesson",
        ),
        migrations.DeleteModel(
            name="SignLanguageLesson",
        ),
    ]
