# Generated by Django 4.2.14 on 2024-09-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_education", "0002_remove_matchingexercises_lesson_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={},
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="order",
        ),
    ]
