# Generated by Django 4.2.14 on 2024-10-16 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_education", "0004_userprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="progress_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "module", "lesson")},
        ),
    ]
