# Generated by Django 4.2.16 on 2024-10-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_education", "0006_alter_userprogress_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="completed_at",
        ),
    ]
